<?php

namespace AppBundle\Repository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends \Doctrine\ORM\EntityRepository
{
	/**
     * @return array
     */
    public function findAll()
    {
        $query = $this->createQueryBuilder('e')
            ->select('e.id, e.name');

        return $query->getQuery()->getArrayResult();
    }

    /**
     * @param $id
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findOneArrayById($id)
    {
        $query = $this->createQueryBuilder('e')
            ->select('e.id, e.name')
            ->where('e.id = :id')
            ->setParameter('id', $id)
            ->setMaxResults(1)
            ->getQuery()->getOneOrNullResult();

        return $query;
    }
}
