<?php

namespace AppBundle\Repository;

/**
 * EmployeeSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeSkillRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $skill
     * @param $level
     * @return array
     */
    public function getAllBySkill($skill, $level)
    {
        $query = $this->createQueryBuilder('es')
            ->select('e.id, e.name, es.level, s.name as skill')
            ->join('AppBundle:Skill', 's', 'WITH', 'es.skill = s.id')
            ->join('AppBundle:Employee', 'e', 'WITH', 'es.employee = e.id')
            ->where('s.id = :skill')
            ->andWhere('es.level >= :level')
            ->andWhere()
            ->orderBy('es.level', 'ASC')
            ->setParameters([
                'skill' => $skill,
                'level' => $level
            ])->getQuery()->getArrayResult();

        return $query;
    }

    /**
     * @param $employee
     * @return array
     */
    public function findAllByEmployee($employee)
    {
        $query = $this->createQueryBuilder('es')
            ->select('s.name, es.level')
            ->join('AppBundle:Skill', 's', 'WITH', 's.id = es.skill')
            ->where('es.employee = :id')
            ->setParameter('id', $employee)
            ->getQuery()->getArrayResult();

        return $query;
    }
}
