<?php

namespace AppBundle\Repository;

/**
 * ManagerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManagerRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findAll()
    {
        $query = $this->createQueryBuilder('m')
            ->select('m.id, m.name')
            ->getQuery()->getArrayResult();

        return $query;
    }
}
