<?php

namespace AppBundle\Repository;

/**
 * ProjectEmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectEmployeeRepository extends \Doctrine\ORM\EntityRepository
{
}
