<?php

namespace AppBundle\Repository;

/**
 * ProjectEmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectEmployeeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $projectId
     * @return array
     */
    public function findAllByProject($projectId)
    {
        $query = $this->createQueryBuilder('pe')
            ->select('pe.id as pe_id, e.id, e.name')
            ->join('AppBundle:Employee', 'e', 'WITH', 'e.id = pe.employee')
            ->where('pe.project = :projectId')
            ->setParameter('projectId', $projectId)
            ->getQuery()->getArrayResult();

        return $query;
    }
}
