<?php

namespace AppBundle\Repository;

/**
 * ProjectEmployeeSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectEmployeeSkillRepository extends \Doctrine\ORM\EntityRepository
{
}
