<?php

namespace AppBundle\Repository;

/**
 * ProjectBacklogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectTaskRepository extends \Doctrine\ORM\EntityRepository
{
}
