<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findAll()
    {
        $query = $this->createQueryBuilder('p')
            ->select('p.id, p.title')
            ->getQuery()->getArrayResult();

        return $query;
    }
}
