<?php

namespace AppBundle\Repository;

/**
 * ProjectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return array
     */
    public function findAll()
    {
        $query = $this->createQueryBuilder('p')
            ->select('p.id, p.title')
            ->getQuery()->getArrayResult();

        return $query;
    }

    public function findOneArrayById($id)
    {
        $query = $this->createQueryBuilder('p')
            ->select('p.id, p.title, p.description, e.name')
            ->join('AppBundle:ProjectEmployee', 'pe', 'WITH', 'p.id = pe.project')
            ->join('AppBundle:Employee', 'e', 'WITH', 'e.id = pe.employee')
            ->where('p.id = :id')
            ->setParameter('id', $id)
            ->setMaxResults(1)
            ->getQuery()->getOneOrNullResult();

        return $query;
    }
}
